# Generated by Django 2.0 on 2018-02-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
